---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: openfunction-demo-db
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
---
apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: silly-demo-videos
spec:
  credentials:
    scheme: postgres
    host: openfunction-demo-db-rw.a-team
    port: 5432
    user: app
    passwordFrom:
      secretKeyRef:
        key: password
        name: openfunction-demo-db-app
    database: app
    parameters:
      sslmode: disable
  schema:
    sql: |
      create table videos (
        id varchar(50) not null,
        title varchar(255) not null,
        primary key (id)
      );
