---
apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: openfunction-demo
  annotations:
    openfunction.io/revision-controller: enable
    openfunction.io/revision-controller-params: |
      type: source
      repo-type: github
      polling-interval: 1m
spec:
  # version: "v2.0.0"
  image: "c8n.io/vfarcic/openfunction-demo"
  imageCredentials:
    name: push-secret
  build:
    builder: openfunction/builder-go:v2.4.0-1.17
    env:
      FUNC_NAME: "SillyDemo"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: "https://github.com/vfarcic/openfunction-demo.git"
      revision: "main"
  serving:
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
    triggers:
      http:
        port: 8080
