---
apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: videos-metadata-function
spec:
  version: "v1.0.0"
  image: "salaboy/videos-metadata:0.1.8"
  serving:
    annotations:
      openfunction.io/enable-dapr: "true"
      openfunction.io/dapr-service-mode: "sidecar"
    template:
      containers:
        - name: function
          imagePullPolicy: IfNotPresent
          env:
            - name: STATESTORE_NAME
              value: openfunction-demo-db
    triggers:
      http:
        port: 8080
