---
apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: silly-demo
spec:
  version: "v1.0.0"
  image: "c8n.io/vfarcic/silly-demo:1.4.58-openfunction"
  imageCredentials:
    name: push-secret
  build:
    builder: openfunction/kaniko-executor:v1.7.0
    dockerfile: Dockerfile
    shipwright:
      strategy:
        kind: ClusterBuildStrategy
        name: kaniko
    srcRepo:
      url: "https://github.com/vfarcic/silly-demo.git"
      revision: "master"
  serving:
    template:
      containers:
        - name: function
          imagePullPolicy: IfNotPresent
    triggers:
      http:
        port: 8080
